### ISSUE TITLE
Example Script Crashes

### ISSUE THREAD

**Issue by dvn0** [Bogdanp/marionette#1]
First off, thanks for writing this library. I'm keen to try it out. 

After launching firefox in headless marionette mode as specified in the README, I try to run the script (the one in the README) and it fails with this output:

```
system*: contract violation
  expected: path-string?
  given: #f
  context...:
   /usr/share/racket/collects/racket/system.rkt:181:19
   /usr/share/racket/collects/racket/system.rkt:174:0: do-system*/exit-code
   /usr/share/racket/collects/racket/system.rkt:210:0: system*40
   "/home/person/Learning/racket/marionette/test.rkt": [running body]
   for-loop
   run-module-instance!125
   perform-require!78
```

I'm running the script with `racket test.rkt`, and this is using Racket v7.0

I am pretty new to Racket, and assuming it's something simple.

**Comment by Bogdanp** [comment]
The example script expects there to be an executable called `open` in your `PATH` (like on `macOS`) and it tries to find said executable and then run `open $FILENAME` as a subprocess here:

https://github.com/Bogdanp/marionette/blob/master/examples/github.rkt#L26

I assume you don't have such an executable so `find-executable-path` returns `#f` which then causes the `system*` call to fail because it expects a path string, but gets a boolean instead. If you're on linux, then I think you can replace `(find-executable-path "open")` with `(find-executable-path "xdg-open")` or something along those lines.

I hope that helps!

**Comment by dvn0** [comment]
Thanks, that's all it was. Makes a lot of sense. :D
